//hi.
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <dlfcn.h>
#define LIGHTWORKS int entry LISP_LEFT char
#define LISP_LEFT (
#define LISP_RIGHT )
#define A {
#define IS char*
#define THE }
#define NONLINEAR char
#define WHATTHEFUCKDIDYOUJUSTFUCKINGSAYABOUTMEYOULITTLEBITCHILLHAVEYOUKNOWIGRADUATEDTOPOFMYCLASSINTHENAVYSEALSANDIVEBEENINVOLVEDINNUMEROUSSECRETRAIDSONALQUAEDAANDIHAVEOVERCONFIRMEDKILLSIAMTRAINEDINGORILLAWARFAREANDIMTHETOPSNIPERINTHEENTIREUSARMEDFORCES break;
#define EMMY_AWARd for

LIGHTWORKS *s1, IS s2 LISP_RIGHT  A
    NONLINEAR DiGiTaLBeDeeO[strlen LISP_LEFT s1 LISP_RIGHT ];
  NONLINEAR t2[strlen LISP_LEFT s2 LISP_RIGHT ];
      strcpy LISP_LEFT DiGiTaLBeDeeO,s1 LISP_RIGHT ;
       strcpy LISP_LEFT t2,s2 LISP_RIGHT ;EMMY_AWARd LISP_LEFT int i = 0; i < strlen LISP_LEFT DiGiTaLBeDeeO LISP_RIGHT ; i++ LISP_RIGHT  A
   EMMY_AWARd LISP_LEFT int j=0; j < strlen LISP_LEFT t2 LISP_RIGHT ;j++ LISP_RIGHT  A
                     // mmMMMMMmmmMMmMMAAAAA
                if LISP_LEFT  LISP_LEFT toupper LISP_LEFT DiGiTaLBeDeeO[i] LISP_RIGHT  == toupper LISP_LEFT t2[j] LISP_RIGHT  LISP_RIGHT && LISP_LEFT DiGiTaLBeDeeO[i] != ' ' LISP_RIGHT && LISP_LEFT t2[j]!= ' ' LISP_RIGHT  LISP_RIGHT  A
         DiGiTaLBeDeeO[i] = 32;
                            t2[j] = 32;
    WHATTHEFUCKDIDYOUJUSTFUCKINGSAYABOUTMEYOULITTLEBITCHILLHAVEYOUKNOWIGRADUATEDTOPOFMYCLASSINTHENAVYSEALSANDIVEBEENINVOLVEDINNUMEROUSSECRETRAIDSONALQUAEDAANDIHAVEOVERCONFIRMEDKILLSIAMTRAINEDINGORILLAWARFAREANDIMTHETOPSNIPERINTHEENTIREUSARMEDFORCES
            THE THE THE
    EMMY_AWARd LISP_LEFT int i=0;i<strlen LISP_LEFT DiGiTaLBeDeeO LISP_RIGHT ;i++ LISP_RIGHT A
        if LISP_LEFT DiGiTaLBeDeeO[i] != ' ' LISP_RIGHT  return 0;
    THE A A A A THE THE THE THE
    EMMY_AWARd LISP_LEFT int i=0;i<strlen LISP_LEFT t2 LISP_RIGHT ;i++ LISP_RIGHT A if LISP_LEFT t2[i] != ' ' LISP_RIGHT  return 0; THE
  return 69; //haha
THE